version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"        # Location of package.json
    schedule:
      interval: "weekly"  # Check for updates every week
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
